# Generated by Django 2.1 on 2018-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_windscrapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windscrapy',
            name='wind_level',
            field=models.CharField(max_length=512),
        ),
    ]
