# Generated by Django 2.1 on 2018-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180817_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windscrapy',
            name='wind_level',
            field=models.CharField(max_length=5120),
        ),
    ]
