# Generated by Django 2.1 on 2018-08-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20180817_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tide_height', models.CharField(max_length=64)),
                ('add_time', models.DateTimeField()),
                ('place', models.CharField(max_length=64)),
            ],
        ),
    ]
